image: python:3.8

cache:
  paths:
  - ~/.cache/pip/

stages:
  - test
  - deploy


test:
  stage: test
  before_script:
  - pip install --upgrade pip
  - pip install coverage==4.5.3
  script:
  - coverage run -m unittest main.py
  - coverage report --omit=main.py
  - coverage html --omit=main.py
  - mkdir public
  - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage

pages:
  stage: deploy
  script:
  - echo 'Publish pages data'
  artifacts:
    paths:
    - public
  only:
  - main