image: python:3.8

cache:
  paths:
  - ~/.cache/pip/

stages:
  - docs
  - test
  - deploy

docs:
  stage: docs
  before_script:
  - pip install sphinx
  script:
  - cd docs
  - export PYTHONPATH
  - make html
  - cd ..
  - mv docs/build/html public/docs
  artifacts:
    paths:
      - public/docs

test:
  stage: test
  before_script:
  - pip install --upgrade pip
  - pip install coverage==4.5.3
  - pip install django
  script:
  - coverage run --source='.' manage.py test
  - coverage report

pages:
  stage: deploy
  script:
  - echo 'Publish pages data'
  artifacts:
    paths:
    - public